server:
  port: 8080
  servlet:
    context-path: /servlet-jsp

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@ics-t-development.cztekutconfc.ap-northeast-2.rds.amazonaws.com:1521:ORCL
    username: root
    password: icstroot
    hikari:
      auto-commit: false
    oracleucp:
      max-pool-size: 5
      initial-pool-size: 3
      min-pool-size: 2
