server:
  port: 8080
  servlet:
    context-path: /servlet-jsp

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.100.70.7:1521:XE
    username: mission303
    password: mission303
    hikari:
      auto-commit: false
      maximum-pool-size: 5