server:
  port: 8080
  servlet:
    context-path: /servlet-jsp

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.100.70.7:1521:XE
    username: student##
    password: student##
    hikari:
      auto-commit: false
    oracleucp:
      max-pool-size: 5
      initial-pool-size: 3
      min-pool-size: 2
